export type TeamEntry = {
  slug: string;
  name: string;
  short: string;
  league: string;
  tier: number;
  gender: "Damen" | "Herren" | "Jugend" | "Mixed";
  description: string;
  accent: "red" | "black" | "gold";
  image?: string;
  trainingTimes?: string[];
  trainerName?: string;
  highlights?: string[];
};

export const teams: TeamEntry[] = [
  {
    slug: "1-mannschaft",
    name: "1. Damen",
    short: "SCU I",
    league: "2. Bundesliga Pro",
    tier: 1,
    gender: "Damen",
    description:
      "Unser Aushängeschild – talentierte, in der eigenen Jugend ausgebildete Spielerinnen auf höchstem nationalen Niveau.",
    accent: "red",
    image: "/team/team-group.jpg",
  },
  {
    slug: "2-mannschaft",
    name: "2. Damen",
    short: "SCU II",
    league: "2. Bundesliga (ab 26/27)",
    tier: 2,
    gender: "Damen",
    description:
      "Aufsteiger 2026/27 – nach der Meisterschaft in der 3. Liga Nord 2025/26 erstmals in der 2. Bundesliga.",
    accent: "black",
    image: "/team/groups/2-mannschaft.jpg",
  },
  {
    slug: "3-mannschaft",
    name: "3. Damen",
    short: "SCU III",
    league: "Oberliga",
    tier: 3,
    gender: "Damen",
    description: "Erfahrung trifft Nachwuchs – Oberliga-Volleyball auf hohem Niveau und enges Bindeglied zur 2. Mannschaft.",
    accent: "gold",
    image: "/team/groups/3-mannschaft.jpg",
    trainingTimes: ["Dienstag 20:00 – 22:00 Uhr", "Donnerstag 20:00 – 22:00 Uhr"],
    highlights: ["Aufstiegsambitionen Richtung 3. Liga", "Mehrfache Bezirksmeisterschaften", "Wichtiger Unterbau für die Bundesliga-Teams"],
  },
  {
    slug: "4-mannschaft",
    name: "4. Damen",
    short: "SCU IV",
    league: "Bezirksliga",
    tier: 4,
    gender: "Damen",
    description: "Ambitionierter Volleyball mit Spaß am Wettkampf – Bezirksliga-Niveau mit jungem Kader.",
    accent: "black",
    image: "/team/groups/4-mannschaft.jpg",
    trainingTimes: ["Montag 19:30 – 21:30 Uhr", "Mittwoch 20:00 – 22:00 Uhr"],
    highlights: ["Junge, hungrige Mannschaft", "Regelmäßige Auf- und Abstiegskämpfe", "Brücke zur Oberliga"],
  },
  {
    slug: "5-mannschaft",
    name: "5. Damen",
    short: "SCU V",
    league: "Bezirksklasse",
    tier: 5,
    gender: "Damen",
    description: "Volleyball für alle Leistungsstufen – von Einsteigerinnen bis Erfahrenen, mit großer Trainingsbeteiligung.",
    accent: "black",
    image: "/team/groups/5-mannschaft.jpg",
    trainingTimes: ["Dienstag 19:30 – 21:30 Uhr"],
    highlights: ["Breite Altersmischung", "Hohe soziale Komponente", "Offen für Quereinsteigerinnen"],
  },
  {
    slug: "6-mannschaft",
    name: "6. Damen",
    short: "SCU VI",
    league: "Kreisliga",
    tier: 6,
    gender: "Damen",
    description: "Teamgeist und Spaß am Sport stehen im Vordergrund – Kreisliga mit familiärer Atmosphäre.",
    accent: "black",
    image: "/team/groups/6-mannschaft.jpg",
    trainingTimes: ["Mittwoch 19:00 – 21:00 Uhr"],
  },
  {
    slug: "7-mannschaft",
    name: "7. Damen",
    short: "SCU VII",
    league: "Kreisklasse A",
    tier: 7,
    gender: "Damen",
    description: "Breitensport-Team mit großer Leidenschaft – ideal für ambitionierte Hobbyspielerinnen.",
    accent: "black",
    image: "/team/groups/7-8-mannschaft.jpg",
    trainingTimes: ["Donnerstag 19:00 – 21:00 Uhr"],
  },
  {
    slug: "8-mannschaft",
    name: "8. Damen",
    short: "SCU VIII",
    league: "Kreisklasse",
    tier: 8,
    gender: "Damen",
    description: "Für neue Spielerinnen – Einstieg in unseren Verein und in den Spielbetrieb.",
    accent: "black",
    trainingTimes: ["Montag 18:30 – 20:00 Uhr"],
  },
  {
    slug: "hobbyliga",
    name: "Hobbyliga",
    short: "Hobbyliga",
    league: "Hobbyliga Grafschaft",
    tier: 13,
    gender: "Mixed",
    description: "Gemischtes Team für ambitionierte Hobbyspieler:innen – regelmäßiger Spielbetrieb in der Hobbyliga Grafschaft.",
    accent: "black",
    image: "/team/groups/hobbyliga.jpg",
  },
  {
    slug: "hobby",
    name: "Hobby",
    short: "Hobby",
    league: "Freizeit-Volleyball",
    tier: 14,
    gender: "Mixed",
    description: "Freizeit-Volleyball im gemischten Team – Spaß am Sport, ohne Liga-Druck, mit festen Trainingszeiten.",
    accent: "gold",
    image: "/team/groups/hobby.jpg",
  },

  {
    slug: "u14",
    name: "U14",
    short: "U14",
    league: "Jugendliga",
    tier: 9,
    gender: "Jugend",
    description: "Unser Bundesliga-Unterbau von morgen – strukturierte Talentförderung mit professionellem Trainerteam.",
    accent: "red",
    image: "/team/groups/u14.jpg",
    trainingTimes: ["Dienstag 17:30 – 19:30 Uhr", "Freitag 17:00 – 19:00 Uhr"],
    highlights: ["Talente aus dem gesamten Grafschafter Raum", "Übergang in den Aktivenbereich vorbereitet", "Regelmäßige Teilnahme an Jugend-Turnieren"],
  },
  {
    slug: "u13",
    name: "U13",
    short: "U13",
    league: "Jugendkreisliga",
    tier: 10,
    gender: "Jugend",
    description: "Talente auf ihrem Weg in die großen Mannschaften – mit Spielfreude und ersten Wettkampferfahrungen.",
    accent: "red",
    image: "/team/groups/u13.jpg",
    trainingTimes: ["Montag 17:00 – 18:30 Uhr", "Donnerstag 17:00 – 18:30 Uhr"],
  },
  {
    slug: "minis",
    name: "Minis",
    short: "Minis",
    league: "Mini-Volleyball",
    tier: 11,
    gender: "Jugend",
    description: "Erste Ballkontakte, erste Erfolge, erster Vereinssport – spielerischer Einstieg ins Volleyball.",
    accent: "gold",
    image: "/team/groups/minis.jpg",
    trainingTimes: ["Mittwoch 16:30 – 17:45 Uhr"],
  },
  {
    slug: "mini-minis",
    name: "Mini-Minis",
    short: "Mini-Minis",
    league: "Ball-Schule",
    tier: 12,
    gender: "Jugend",
    description: "Koordination & Spielfreude für unsere Jüngsten – die ersten Schritte mit dem Ball.",
    accent: "gold",
    image: "/team/groups/minis.jpg",
    trainingTimes: ["Freitag 16:00 – 17:00 Uhr"],
  },
];
